go.mod
go.sum

Update the containerd dependency to fix a known vulnerability.
https://github.com/NetApp/astra-connector-operator/security/dependabot/1

Update containerd dependency for security issues

---

README.md

Add Security Best Practices section in README, to inform users of ways they can improve the security of the connector post deployment.

Add Security Best Practices section to README

---

.github/workflows/cicd.yml
Makefile

Additions to github actions:
When building on master:
* Builds an install bundle with install exe and image tar
* Creates a Github Draft Release, using the install bundle as an artifact there
* Install bundle is versioned the same as the operator
In order to create the full release, one of us just needs to navigate to the releases page and click the button.
Example Draft Release: https://github.com/NetApp/astra-connector-operator/releases

Add install bundle git action

---

common/constants.go
deployer/connector/astra_connect_test.go
deployer/connector/nats_test.go
deployer/connector/natssync_client_test.go
details/operator-sdk/config/samples/astra_v1_astraconnector.yaml

Updating default images so it matches what is in docker.io and in my docker.repo.eng.netapp.com/oscarr/arch3.0. Now the users won't need to specify images unless they want to test a different non default image. And the only difference between docker.io and internal image is you'll need a secret to pull connector image from docker.io

Updating Default of Images

---

details/operator-sdk/astraconnector_operator.yaml

Hitting an issue in OCP where the operator is just above the memory: 100Mi. We need to set these limit highers, will set to match acc operator for now with a spike later on in phase two when we include deployment of Neptune too.

Astractl 27847 limits to match acc operator

---

common/constants.go
deployer/connector/nats.go
deployer/connector/nats_test.go

On openshift, we observed that the default 1MB nats payload size is not good enough. this bumps the nats payload size to 8mb
Testing - deployed nats_config:
```
code/astra-connector-operator [bump-nats-payload-size●] » k get cm -n astra-connector nats-configmap -o yaml
apiVersion: v1
data:
nats.conf: |
pid_file: "/var/run/nats/nats.pid"
http: 8222
max_payload: 8388608
cluster {
port: 6222
routes [
nats://nats-0.nats-cluster:6222
nats://nats-1.nats-cluster:6222
nats://nats-2.nats-cluster:6222
]
cluster_advertise: $CLUSTER_ADVERTISE
connect_retries: 30
}
```

ASTRACTL-27894 bump nats max_payload

---

app/conf/config.go

This changes back the flag to not deploy neptune by default

Do not Deploy neptune by default

---

.config.yaml.sample
.github/workflows/cicd.yml
app/conf/config.go
details/operator-sdk/controllers/astraconnector_controller.go
details/operator-sdk/controllers/connector.go
details/operator-sdk/controllers/status_strings.go

Skip connector registration with nats and astra when `SkipAstraRegistration` feature flag is set to `true`. This is for internal use only and will be set to false by default

Astractl 27233 - Skip nats and astra registration based on feature flag

---

common/constants.go

When Users install connector-operator, with ACOP_FEATUREFLAGS_DEPLOYNEPTUNE=true env var, connector operator should be sending an additional connector capability `neptuneV1` to astra

ASTRACTL-28473 Connector operator to send neptuneV1 capability conditionally

---

.github/workflows/cicd.yml
scripts/create_default_images_manifest.go

This adds a default-image manifest txt file of the default images used by connector.
The manifest filename is: default-image-manifest-VERSION.manifest
I added "default-" because these images can technically be overridden . 
example contents:
`netappdownloads.jfrog.io/docker-astra-control-staging/arch30/neptune/astra-connector:1.0.202307311828
netappdownloads.jfrog.io/docker-astra-control-staging/arch30/neptune/natssync-client:2.1.202306281610
netappdownloads.jfrog.io/docker-astra-control-staging/arch30/neptune/nats:2.8.4-alpine3.15
netappdownloads.jfrog.io/docker-astra-control-staging/arch30/neptune/neptune:main-b65bdb9-July21`

add manifest file

---

app/deployer/connector/astra_connect.go
details/operator-sdk/controllers/astraconnector_controller.go

ASTRACTL-29228 
APP cluster can have any sort of permission in an app, and when we go to clone that app we need to support any permission, we were missing the delete collection from the verb,

ASTRACTL-29228 adding * verbs

---

Makefile

Removes neptune crds and namespace from the 23.10 release bundle

ASTRACTL-28939 Remove neptune crds and ns from the 23.10 bundle

---

details/operator-sdk/controllers/astraconnector_controller.go
details/operator-sdk/controllers/connector.go
details/operator-sdk/controllers/neptune.go

Modifies requeue timeouts depending on error case. We want to timeout for some configurable time if there is an error to allow the user to view the error condition.

modify requeues

---

app/deployer/neptune/neptuneV2.go

Correction from previous PR.  Need the app label on the neptune pod, not the deployment.

ASTRACTL-29909:move label from deploy to pod

---

common/constants.go
scripts/create_default_images_manifest.go

Fix to include the latest version of neptune controller in the manifest (as of today, static version is being included). Also adds additional neptune related images to the manifest

Include additonal neptune images in the manifest file

---

app/register/register.go
app/register/register_test.go

We were losing the clusteID (not getting saved in the CR status) if the POST /cluster call succeeded but the managed cluster call failed.
easy fix

save cluster ID

---

common/constants.go

Reverts NetApp/astra-connector-operator#206
This had unintended consequences when pairing these changes with the current state of the Polaris repo, breaking the entire 3.0 register workflow. Reverting until I can get this stuff fully worked out.

Revert "ASTRACTL-30644: replace relayV1 with connectorV2 capability"

---

app/conf/config.go
app/conf/config_test.go

This PR fixed the mixups of PodSecuirtyContext and SecurityContext when sets up astra connector components

Fixed the mixups of podSecurityContext and SecurityContext

---

app/deployer/neptune/neptuneV2.go

ACO is not always sending the NEPTUNE_TAG env variable to neptune-controller-manager

ASTRACTL-31411 Fix issue with NEPTUNE_TAG env variable

---

app/conf/config.go
details/k8s/cluster_type_checker.go

This PR
- bumps resource wait timeout, it takes a bit longer on the ocp clusters running on VMs
- do not log an error for AKS cluster type check if not found

bump resource timeout

---

details/operator-sdk/config/manager/manager.yaml

https://jira.ngage.netapp.com/browse/ASTRACTL-31541
There will be a subsequent trident-asup PR for collecting all the logs from the connector operator namespace.  But we don't want to hard code namespaces.  So first adding a label with a key/value that will be the same and present for every connector operator deploy.  The connector ASUP code will use the label to find the operator pod and its namespace.
As expected, operator deployed w/ change has the new label in pod description:
Name:             operator-controller-manager-5b8465778d-g6wtk
Namespace:        astra-connector-operator
Priority:         0
Service Account:  operator-controller-manager
Node:             dev-ol-astra-enterprise-10-wrkr-3/10.193.63.213
Start Time:       Fri, 09 Feb 2024 12:09:01 -0700
Labels: …

ASTRACTL-31541:Add label for ASUP log collection use

---

app/deployer/neptune/neptuneV2.go
app/deployer/neptune/neptune_test.go
common/constants.go

In Order to properly delete and deploy rbac proxy service we are changing it to be deployed by the operator

Cherrypick Rbac Service to be deployed by operator

---

app/register/register.go
app/register/register_test.go

Sanitize input for cloudBridgeURL so that a trailing slash does not cause the application to break.

remove trailing slash from cloudbridgeurl

---

app/register/register.go

A bug in the retry mechanism led to empty body in successive registration requests. This PR ensures that NewRequestWithContext always gets a valid io.Reader.
https://jira.ngage.netapp.com/browse/ASTRACTL-31482

ASTRACTL-31482: fix retries in registration

---

app/register/register.go

This removes an redundancy in stream and byte array creation introduced in the previous [PR](https://github.com/NetApp/astra-connector-operator/pull/277) that fixed the retry logic in registration.

ASTRACTL-31482: fix registration retries v2

---

app/deployer/connector/astra_connect.go

[ASTRACTL-28885](https://jira.ngage.netapp.com/browse/ASTRACTL-28885)
This PR includes the `shutdownsnapshots` resource to the role.

ASTRACTL-28885 include shutdownsnapshots role

---

app/deployer/connector/astra_connect_natless.go

closes ASTRACTL-32120
* updates environment in the natless connector deployer to pass in the memory limits set on the container as an env variable.

ASTRACTL-32120: Connector : SPIKE - Explore more efficient options to sending this(Latest Resources) at scale (batching, websockets?)

---

.github/workflows/cicd.yml
app/conf/config.go
details/operator-sdk/api/v1/astraconnector_types.go
details/operator-sdk/config/crd/bases/astra.netapp.io_astraconnectors.yaml
details/operator-sdk/controllers/astraconnector_controller_test.go

This turns on Natless deployment on by default from operator, also CloudID and ClusterID are now required since Connector will through errors with out them

ASTRACTL-32735 turning on natless from old operator

---

cluster-install/neptune.yaml
details/operator-sdk/config/manager/manager.yaml

This adds the namespace creation back to `manager.yaml`, but removes it from `neptune.yaml` to continue preventing a clash when using the unified installer script.

ASTRACTL-32896: revert namespace removal from manager yaml

---

cluster-install/kustomization.yaml
cluster-install/neptune.yaml
details/operator-sdk/config/default/kustomization.yaml
details/operator-sdk/config/namespace/kustomization.yaml
details/operator-sdk/config/namespace/namespace.yaml
details/operator-sdk/config/unified-installer-script/kustomization.yaml

This PR does a few things:
- Adds back the namespace resource to `neptune.yaml` to unblock the polaris qual pipeline (would have to wait for a neptune PR to merge otherwise)
- Separates the namespace resource in `details/operator-sdk/config/default/manager.yaml` into its own folder so that it can be excluded from `cluster-install/kustomization.yaml`
- Add a new `details/operator-sdk/config/unified-install-script/kustomization.yaml` that gets pulled in by the cluster-install kustomization file
- Update relevant kustomization files

ASTRACTL-32896: fix namespace yaml situation

---

app/deployer/neptune/neptuneV2.go
details/operator-sdk/config/manager/manager.yaml

We are seeing leader election crashing in scale scenarios. Chatted with @chrisophus and we decided to disable leader election and change the update strategy to address these issues. This makes the changes for both the connector operator and the Neptune controller.
[ASTRACTL-33429](https://jira.ngage.netapp.com/browse/ASTRACTL-33429)
[ASTRACTL-33388](https://jira.ngage.netapp.com/browse/ASTRACTL-33388)

ASTRACTL-33429: Disable leader election and set update strategy to recreate

---

cluster-install/install.sh

- Add help message and arg processing
- Add `IMAGE_PULL_SECRET` to `trident-operator` and/or `torc` during upgrades if they're missing from the list
- Add prompt/warning if `IMAGE_PULL_SECRET=""` and the user is using custom images
Tested these changes through 4 scenarios:
1. Greenfield (no initial connector/trident install)
2. Brownfield (no initial connector, but pre-existing trident at 23.07)
3. Brownfield, but DO_NOT_MODIFY_EXISTING_TRIDENT=true (same setup as 2nd test)
4. Greenfield at version 23.07 + modified pull secrets + rerun script with upgrade to verify that pull secrets are properly added

ASTRACTL-32772: pull secret fix

---

unified-installer/astra-unified-installer.sh

Fixes a "division by zero" ark error. The root cause still confuses me but I was unable to reproduce it with these changes.
I also adjusted the math and added a comment of how we were calculating.

astractl-33663: scale memory limits based on snpahot/backup count

---

unified-installer/astra-unified-installer.sh

Fixes hostAliasIp option so it doesn't get entered under the wrong place in the spec

fix hostAliasIp out of place in CR

---

app/deployer/connector/astra_connect_natless.go

closes ASTRACTL-33864
* updates astraconnet clusterRole, adds permissions to get/list clusterRoles

ASTRACTL-33864: astra-connector: unable to detect AKS flavor correctly.

---

app/deployer/connector/astra_connect_natless.go

closes ASTRACTL-33890
* updates astraconnect role with permissions to get, list clusteroperators.config.openshift.io

ASTRACTL-33890: astra-connector: unable to detect OCP flavor correctly.

---

unified-installer/astra-unified-installer.sh

- Fix `kubectl get version` warnings being interpreted as errors for `
- Fix `kubectl auth can-i` errors being interpreted as the user not having admin access

ASTACTL-32772: kubectl version/permission fixes
