- README.md
- controllers/astraconnector_controller.go
- controllers/configmaps.go
- controllers/deployments.go
- controllers/rolebindings.go
- controllers/roles.go
- controllers/serviceaccounts.go
- controllers/services.go
- controllers/statefulsets.go
- controllers/suite_test.go
- deployer/deployer.go
- deployer/factory.go
- echo_client/echo-client.go
- go.mod
- httpproxy_client/httpproxy_client.go
- main.go
- nats/nats.go
- natssync_client/natssync_client.go
- register/register.go
Rename imports from astraagent to astra-controller
> Rename imports from astraagent to astra-controller

- common/constants.go
Change the cloud bridge default url to staging
> change the cloud bridge default url to staging

- LICENSE
- hack/boilerplate.go.txt
Moded the boiler plate to be less verbose, we only need copy right
> Added full license text in license file per Legal request

- README.md
- api/v1/astraagent_types.go
- astraconnector_operator.yaml
- config/crd/bases/netapp.astraconnector.com_astraconnectors.yaml
- controllers/astraconnector_controller.go
- controllers/configmaps.go
- controllers/deployments.go
- controllers/rolebindings.go
- controllers/roles.go
- controllers/serviceaccounts.go
- controllers/services.go
- controllers/statefulsets.go
- controllers/status_strings.go
Add a status field for operator crd
> Add a status field for operator crd

- README.md
- controllers/astraconnector_controller.go
- Fetch astra connector before status update
- Avoid reconcile for status update
> fetch astra connector before status update and avoid reconcile for status updates

- register/register.go
update astraConnectorID to locationID
> update astraConnectorID to locationID

- .github/workflows/cicd.yml
- astraconnector_operator.yaml
Fixes a cicd issue due to astraconnector_operator.yaml missing
> Add astraconnector operator yaml

- scripts/create-image-tar.sh
Updated paths inside create-image-tar.sh. These files moved when "main" branch was created
> update yaml paths in  create-image-tar.sh

- .github/workflows/cicd.yml
git push --set-upstream origin update-cicd-tar-path
> Update cicd tar path

- .github/workflows/cicd.yml
- Makefile
Remove git pull in cicd code, causes issue seen here:
https://github.com/NetApp/astra-connector-operator/actions/runs/5281187125/jobs/9554828115
> Remove git pull cicd

- .gitignore
- details/k8s/k8s_util.go
- details/k8s/k8s_util_test.go
- details/operator-sdk/astraconnector_operator.yaml
- details/operator-sdk/config/manager/kustomization.yaml
- details/operator-sdk/controllers/astraconnector_controller.go
- details/operator-sdk/controllers/connector.go
- details/operator-sdk/controllers/deployer.go
Cluster Scoped resources are not deleted when uninstalling the connector, this PR fixes that issue
> ASTRACTL-27766 Delete cluster-scoped resources on CR delete

- .github/workflows/cicd.yml
- Makefile
Adds code coverage report to PRs and lints
> Add lint and coverage

- .github/workflows/cicd.yml
- details/operator-sdk/controllers/astraconnector_controller.go
- details/operator-sdk/controllers/connector.go
- details/operator-sdk/controllers/suite_test.go
- installer/install.go
- register/register.go
- test/test-util/test_util.go
> fixes lint issues;

- details/operator-sdk/astraconnector_operator.yaml
- details/operator-sdk/config/manager/manager.yaml
Updating them in the correct spot
> adding some limits 

- common/constants.go
- deployer/connector/natssync_client_test.go
update natssync client to pull in a bug fix
> update natssync client

- details/operator-sdk/api/v1/astraconnector_validator.go
- details/operator-sdk/api/v1/astraconnector_validator_test.go
- details/operator-sdk/config/samples/astra_v1_astraconnector.yaml
- details/operator-sdk/controllers/astraconnector_controller.go
- util/go_util.go
This adds a validation that disallows deploying to the default namespace.
> Disable deploying to default namespace

- .github/workflows/cicd.yml
- Makefile
- conf/config_test.go
- deployer/neptune/neptune_test.go
- installer/install_test.go
- register/register_test.go
- util/go_util_test.go
Adds test files for better coverage reports
> ASTRACTL-27932 Accurate test coverage

- Makefile
- details/operator-sdk/controllers/astraconnector_controller_test.go
- details/operator-sdk/controllers/suite_test.go
Adds integration test for validating that connector, nats, and natssync client have been created with the AstraConnector custom resource.
> Astractl 27158 envtest

- scripts/unmanage.py
Adds convenience script for unmanaging a cluster. To be used in development (and probably down the line by cicd) only
> Astractl 26298 unmanage script

- .github/workflows/cicd.yml
- app/deployer/connector/astra_connect_test.go
- app/deployer/connector/natssync_client_test.go
- common/constants.go
update connector and natssync-client images to use api for locationID
> update connector and natssync-client images to use api for locationID

- app/deployer/neptune/neptuneV2.go
- common/constants.go
- details/operator-sdk/config/samples/neptune_v1_crd.yaml
This PR sends needed Env variables to Neptune Controller in order for it to be able to pull images it needs to pull.
This also updates neptune to latest version.
> adding env and updating neptune

- app/deployer/connector/astra_connect_test.go
- app/deployer/connector/nats.go
- app/deployer/connector/nats_test.go
- common/constants.go
generate nats config dynamically and update connector image
> generate nats config dynamically and update connector image

- common/constants.go
- details/operator-sdk/config/samples/neptune_v1_crd.yaml
> Updating to f674741

- common/constants.go
- details/operator-sdk/config/samples/neptune_v1_crd.yaml
Update Neptune to point to latest in Neptune Main
> Neptune 38862ed

- common/constants.go
- details/operator-sdk/config/samples/neptune_v1_crd.yaml
Updating Neptune to the latest as of Sept 6th
> Update neptune 5fc4e2e

- common/constants.go
- details/operator-sdk/config/samples/neptune_v1_crd.yaml
Updating Neptune 73846b5 latest for Sept 11.
> Updating Neptune 73846b5

- app/deployer/connector/astra_connect_test.go
- common/constants.go
> Connector image update

- app/deployer/connector/astra_connect_test.go
- common/constants.go
update connector image to pull in a bug fix
> update connector image to pull in a bug fix

- Makefile
Concat to end of the  (BUILD_DIR)/astraconnector_operator.yaml
> concat fix makefile

- app/deployer/connector/nats.go
- app/deployer/connector/nats_test.go
- app/deployer/connector/natssync_client_test.go
- common/constants.go
- Update nats image
- Update natssync-client image
- update nats replica to 1
> update images, nats replica

- app/deployer/connector/astra_connect.go
- details/operator-sdk/config/rbac/role.yaml
- details/operator-sdk/controllers/astraconnector_controller.go
Trying this again but changing the role.yaml
> Astractl 29228 permissions

- app/deployer/connector/nats.go
- app/deployer/connector/nats_test.go
Nats to pull from same place as the rest of the images.
> Astractl 29576 nats image

- app/deployer/connector/nats.go
- app/deployer/connector/nats_test.go
Reverts NetApp/astra-connector-operator#139
> Revert "Astractl 29576 nats image"

- app/deployer/connector/nats.go
- app/deployer/connector/nats_test.go
Reverts NetApp/astra-connector-operator#142
> Revert "Revert "Astractl 29576 nats image""

- app/deployer/connector/nats.go
- app/deployer/connector/nats_test.go
* fixing nats image
* fixing unit test
> Astractl 29576 nats image (#139)

- details/operator-sdk/controllers/astraconnector_controller.go
ignore status update error. we probably need to fix this in the future
> read error

- README.md
- common/constants.go
- controllerconfig.yaml
This update the release bundle and constants with the images that we have been testing with. Additionally the docs have been updated to match the format we posting on our official docs page.
> Astractl 29850 release bundle

- app/deployer/connector/astra_connect_test.go
- common/constants.go
Updating connector image to 1.0.202311280654
> Updating connector image to 1.0.202311280654

- app/deployer/connector/astra_connect_test.go
- common/constants.go
updating connnector image to .202311291720
> updating connnector image to .202311291720

- details/operator-sdk/controllers/astraconnector_controller.go
Adding logic to not requeque and removing managed check that's preventing the reconcile
> Kubectl Edit doesn't change ASUP URL or enablement. 

- details/operator-sdk/config/manager/manager.yaml
> ASTRCTL-28974 adds kubesec stuff that I missed

- app/deployer/connector/astra_connect_test.go
- details/operator-sdk/controllers/astraconnector_controller.go
- details/operator-sdk/controllers/astraconnector_controller_delete_test.go
- details/operator-sdk/controllers/constants.go
* create manual list of resources to delete and wait for them to be removed
> Remove neptune resources on `AstraConnector` teardown

- Dockerfile
- app/conf/config.go
- app/conf/config_test.go
- app/deployer/connector/astra_connect.go
- app/deployer/connector/nats.go
- app/deployer/connector/nats_test.go
- app/deployer/connector/natssync_client.go
- app/deployer/connector/natssync_client_test.go
- app/deployer/neptune/neptune.go
- app/deployer/neptune/neptuneV2.go
- app/deployer/neptune/neptune_test.go
- common/constants.go
- deploy/base/astra-connector/deployment.yaml
- deploy/base/nats/statefulset.yaml
- details/operator-sdk/config/manager/manager.yaml
- details/operator-sdk/config/samples/neptune.yaml
This PR is to fix the issues deploy astra connector/neptune on openshift cluster.
> Reworked nonRootUser use

- details/operator-sdk/controllers/astraconnector_controller.go
Wraps unmanage in check to see if cluster is registered
> only unmanage when registered = true

- common/constants.go
- scripts/create_default_images_manifest.go
Include asup_tag that comes from the neptune respository in the manifest file for dark site + replaced reading from files with "go embed"
> ASTRACTL-30908 Include asup_tag in the manifest file for dark site

- README.md
Small PR updating the CR field 'skipTLSValidation' shown in the README
https://jira.ngage.netapp.com/browse/ASTRACTL-28287
> Update CR field 'skipTLSValidation' readme text

- README.md
ASTRACTL-28287: Updating readme text for CR field 'skipTLSValidation'
> ASTRACTL-28287: Update CR field 'skipTLSValidation' readme text (#275)

- app/deployer/connector/nats_test.go
- app/deployer/connector/natssync_client_test.go
- common/constants.go
Update default image registry to ACS Prod Container Registry
> ASTRACTL-30625 Update default image registry to ACS Prod Container Registry

- details/operator-sdk/api/v1/astraconnector_types.go
- scripts/create_default_images_manifest.go
> default asup off

- common/constants.go
Fix astra-connector-operator registry
> ASTRACTL-30625 connector operator fix

- details/operator-sdk/config/manager/manager.yaml
remove from namespace from manager
> remove from namespace from manager

- details/operator-sdk/api/v1/astraconnector_types.go
- details/operator-sdk/config/crd/bases/astra.netapp.io_astraconnectors.yaml
- details/operator-sdk/controllers/astraconnector_controller.go
- details/operator-sdk/controllers/deployer.go
> another quick fix

- .gitignore
- cluster-install/README.md
- cluster-install/install.sh
This ports over the Unified Install script from the Astra Connector repo. The only changes from the version over there are:
- Example config updated to new image values
- Removed some TODOs from the file that were outdated
> ASTRACTL-33425: move unified install script from AC repo to ACOP repo

- unified-installer/astra-unified-installer.sh
Use public repo to install trident so we don't get asked for creds. Left some todo for when we have24.06 image
> Use public repo to install trident so we don't get asked for creds

- app/deployer/connector/astra_connect_natless.go
- deploy/base/astra-connector/clusterrole.yaml
> ASTRACTL-33731: add missing roles

- app/deployer/connector/astra_connect_natless.go
- app/deployer/neptune/neptuneV2.go
Adding rules to mutate function so that incase the role exist the rules are properly updates.
> Proper update of Role and clusterRoles

- unified-installer/astra-unified-installer.sh
Cosmetic changes:
- `Trident` -> `Astra Trident`
- `ACP` -> `Astra Control Provisioner`
> ASTRACTL-32772: rename Trident -> Astra Trident
